# Generated by meteor-tupperware quickstart script 0.1.2
# https://github.com/chriswessels/meteor-tupperware

# Inherit from chriswessels/meteor-tupperware image
FROM quay.io/chriswessels/meteor-tupperware

# The maintainer of your app image
MAINTAINER Alexsandro
